<?php
$sp_boxes = array ( 
'Generator' => array (
array( 'Checkbx2', 'Movie',  ),
array( 'Movie', __('Generate Movie'), 'button' ),
array( 'movie_desc', 'movie_desc', 'moviedescription' ),
array( 'Checkbx3', 'TV' ),
array( 'TV', __('Generate Series'), 'button' ),	
array( 'tv_desc', 'tv_desc', 'tvdescription' ),

),
'Informazioni' => array (
        array( 'inizio_1', 'inizio_1', 'inizio' ),
		array( 'imdb_id', 'IMDb' ),
		array( 'id', 'TMDB' ),
        array( 'Title', 'Title' ),
        array( 'originalTitle', 'originalTitle' ),
        array( 'Plot', 'Plot' ),
        array( 'name', 'Tv Show Name' ),
        array( 'genres', 'Genre' ),
		array( 'Poster', 'Poster' ),
		array( 'Rated', 'Rated' ), 
		array( 'Music', 'Music' ),
		array( 'Language', 'Language' ),
		array( 'episode_run_time', 'episode_run_time' ),
		array( 'Metascore', 'Metascore' ),
        //array( 'vote_average', 'vote_average' ),
		array( 'imdbVotes', 'imdbVotes' ),
		array( 'Awards', 'Awards' ), 
		array( 'Country', 'Country' ),
		array( 'vote_average', 'vote_average' ),
		array( 'vote_count', 'vote_count' ),
		array( 'homepage', 'homepage' ),
		array( 'overview', 'overview' ), 
		array( 'poster_path', 'poster_path' ), 
		array( 'backdrop_path', 'backdrop_path' ), 
		array( 'first_air_date', 'first_air_date' ), 
		array( 'last_air_date', 'last_air_date' ), 
		array( 'number_of_episodes', 'number_of_episodes' ),
		array( 'number_of_seasons', 'number_of_seasons' ),
		array( 'tomatoMeter', 'tomatoMeter' ),
		array( 'tomatoUserMeter', 'tomatoUserMeter' ),
		array( 'tomatoUserRating', 'tomatoUserRating' ),
		array( 'tomatoUserReviews', 'tomatoUserReviews' ),
		array( 'BoxOffice', 'BoxOffice' ),
		array( 'Production', 'Production' ),
		array( 'Website', 'Website' ),
		array( 'popularity', 'popularity' ), 
		array( 'status', 'status' ), 
		array( 'budget', 'budget' ), 
		array( 'revenue', 'revenue' ),
		array( 'soundtrackurl', 'soundtrackurl' ),
		array( 'tagline', 'tagline' ),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
		array( 'images', 'images', 'textarea' ),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
		array( 'cast', 'cast', 'textarea' ),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
		array( 'crew', 'crew', 'textarea' ),
        array( 'fine_1', 'fine_1', 'fine' ),
),
'Openload' => array (
        array( 'fullhd', '1080p'),
        array( 'hd', '720p'),
        array( 'sd', '360p'),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
),

'Trailer' => array (
        array( 'youtube_id', 'youtube_id'),
        array( 'imdbRating', 'imdbRating' ),
		array( 'Runtime', 'Runtime' )
),



'SerieTV' => array (
        array( 'inizio_1', 'inizio_1', 'inizio' ),
		array( 'e1_1', '1 '.season.' 1' ),
		array( 'e1_2', '2' ),
		array( 'e1_3', '3' ),
		array( 'e1_4', '4' ),
		array( 'e1_5', '5' ),
		array( 'e1_6', '6' ),
		array( 'e1_7', '7' ),
		array( 'e1_8', '8' ),
		array( 'e1_9', '9' ),
		array( 'e1_10', '10' ),
		array( 'e1_11', '11' ),
		array( 'e1_12', '12' ),
		array( 'e1_13', '13' ),
		array( 'e1_14', '14' ),
		array( 'e1_15', '15' ),
		array( 'e1_16', '16' ),
		array( 'e1_17', '17' ),
		array( 'e1_18', '18' ),
		array( 'e1_19', '19' ),
		array( 'e1_20', '20' ),
		array( 'e1_21', '21' ),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
		array( 'e2_1', '1 '.season.' 2' ),
		array( 'e2_2', '2' ),
		array( 'e2_3', '3' ),
		array( 'e2_4', '4' ),
		array( 'e2_5', '5' ),
		array( 'e2_6', '6' ),
		array( 'e2_7', '7' ),
		array( 'e2_8', '8' ),
		array( 'e2_9', '9' ),
		array( 'e2_10', '10' ),
		array( 'e2_11', '11' ),
		array( 'e2_12', '12' ),
		array( 'e2_13', '13' ),
		array( 'e2_14', '14' ),
		array( 'e2_15', '15' ),
		array( 'e2_16', '16' ),
		array( 'e2_17', '17' ),
		array( 'e2_18', '18' ),
		array( 'e2_19', '19' ),
		array( 'e2_20', '20' ),
		array( 'e2_21', '21' ),
		array( 'e3_1', '1 '.season.' 3' ),
		array( 'e3_2', '2' ),
		array( 'e3_3', '3' ),
		array( 'e3_4', '4' ),
		array( 'e3_5', '5' ),
		array( 'e3_6', '6' ),
		array( 'e3_7', '7' ),
		array( 'e3_8', '8' ),
		array( 'e3_9', '9' ),
		array( 'e3_10', '10' ),
		array( 'e3_11', '11' ),
		array( 'e3_12', '12' ),
		array( 'e3_13', '13' ),
		array( 'e3_14', '14' ),
		array( 'e3_15', '15' ),
		array( 'e3_16', '16' ),
		array( 'e3_17', '17' ),
		array( 'e3_18', '18' ),
		array( 'e3_19', '19' ),
		array( 'e3_20', '20' ),
		array( 'e3_21', '21' ),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
		array( 'e4_1', '1 '.season.' 4' ),
		array( 'e4_2', '2' ),
		array( 'e4_3', '3' ),
		array( 'e4_4', '4' ),
		array( 'e4_5', '5' ),
		array( 'e4_6', '6' ),
		array( 'e4_7', '7' ),
		array( 'e4_8', '8' ),
		array( 'e4_9', '9' ),
		array( 'e4_10', '10' ),
		array( 'e4_11', '11' ),
		array( 'e4_12', '12' ),
		array( 'e4_13', '13' ),
		array( 'e4_14', '14' ),
		array( 'e4_15', '15' ),
		array( 'e4_16', '16' ),
		array( 'e4_17', '17' ),
		array( 'e4_18', '18' ),
		array( 'e4_19', '19' ),
		array( 'e4_20', '20' ),
		array( 'e4_21', '21' ),
		array( 'e5_1', '1 '.season.' 5' ),
		array( 'e5_2', '2' ),
		array( 'e5_3', '3' ),
		array( 'e5_4', '4' ),
		array( 'e5_5', '5' ),
		array( 'e5_6', '6' ),
		array( 'e5_7', '7' ),
		array( 'e5_8', '8' ),
		array( 'e5_9', '9' ),
		array( 'e5_10', '10' ),
		array( 'e5_11', '11' ),
		array( 'e5_12', '12' ),
		array( 'e5_13', '13' ),
		array( 'e5_14', '14' ),
		array( 'e5_15', '15' ),
		array( 'e5_16', '16' ),
		array( 'e5_17', '17' ),
		array( 'e5_18', '18' ),
		array( 'e5_19', '19' ),
		array( 'e5_20', '20' ),
		array( 'e5_21', '21' ),
		array( 'spazio_1', 'spazio_1', 'spazio' ),
		array( 'e6_1', '1 '.season.' 6' ),
		array( 'e6_2', '2' ),
		array( 'e6_3', '3' ),
		array( 'e6_4', '4' ),
		array( 'e6_5', '5' ),
		array( 'e6_6', '6' ),
		array( 'e6_7', '7' ),
		array( 'e6_8', '8' ),
		array( 'e6_9', '9' ),
		array( 'e6_10', '10' ),
		array( 'e6_11', '11' ),
		array( 'e6_12', '12' ),
		array( 'e6_13', '13' ),
		array( 'e6_14', '14' ),
		array( 'e6_15', '15' ),
		array( 'e6_16', '16' ),
		array( 'e6_17', '17' ),
		array( 'e6_18', '18' ),
		array( 'e6_19', '19' ),
		array( 'e6_20', '20' ),
		array( 'e6_21', '21' ),
        array( 'fine_1', 'fine_1', 'fine' )
),

);
?>